name: Linux build

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
    - run: |
        export UID
        mkdir -p ~/.cache/bazel
        mkdir -p ~/.cache/bazelisk
        docker compose run build
      env:
        GITHUB_TOKEN: ${{ github.token }}
        BAZEL_BUILD_OPTIONS: --config=rbe --config=bes --config=remote-ci
