name: macOS build

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
    - main


jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - run: |
        brew install coreutils gnu-tar
    - run: |
        ./build-website.sh
