name: macOS build

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
    - main


jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - run: |
        brew install coreutils gnu-tar
    - run: |
        ./build-website.sh
